# coding: utf-8

"""
    CvTool Image API

    Image services.

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cvtool_images_client
from cvtool_images_client.rest import ApiException
from cvtool_images_client.models.vision_annotations import VisionAnnotations


class TestVisionAnnotations(unittest.TestCase):
    """ VisionAnnotations unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVisionAnnotations(self):
        """
        Test VisionAnnotations
        """
        model = cvtool_images_client.models.vision_annotations.VisionAnnotations()


if __name__ == '__main__':
    unittest.main()
