# coding: utf-8

"""
    Kingpick Image API

    Image  services.

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cvtool_images_client
from cvtool_images_client.rest import ApiException
from cvtool_images_client.models.image_request import ImageRequest


class TestImageRequest(unittest.TestCase):
    """ ImageRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageRequest(self):
        """
        Test ImageRequest
        """
        model = cvtool_images_client.models.image_request.ImageRequest()


if __name__ == '__main__':
    unittest.main()
