# coding: utf-8

"""
    CvTool Image API

    Image services.

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cvtool_images_client
from cvtool_images_client.rest import ApiException
from cvtool_images_client.models.image_list_response import ImageListResponse


class TestImageListResponse(unittest.TestCase):
    """ ImageListResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageListResponse(self):
        """
        Test ImageListResponse
        """
        model = cvtool_images_client.models.image_list_response.ImageListResponse()


if __name__ == '__main__':
    unittest.main()
