# coding: utf-8

"""
    CvTool Image API

    Image services.

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cvtool_images_client
from cvtool_images_client.rest import ApiException
from cvtool_images_client.apis.image_api import ImageApi


class TestImageApi(unittest.TestCase):
    """ ImageApi unit test stubs """

    def setUp(self):
        self.api = cvtool_images_client.apis.image_api.ImageApi()

    def tearDown(self):
        pass

    def test_add(self):
        """
        Test case for add

        
        """
        pass

    def test_list_all(self):
        """
        Test case for list_all

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
