# coding: utf-8

"""
    Kingpick Image API

    Image  services.

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .annotation import Annotation
from .image_request import ImageRequest
from .image_response import ImageResponse
