# coding: utf-8

"""
    Kingpick Image API

    Image  services.

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.annotation import Annotation
from .models.image_request import ImageRequest
from .models.image_response import ImageResponse

# import apis into sdk package
from .apis.image_api import ImageApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
